#! /usr/bin/env sh

# SPDX-License-Identifier: BlueOak-1.0.0
# SPDX-FileCopyrightText: 2025 Saulius Krasuckas <saulius2_at_ar-fi_point_lt> | sskras

# Tool to iterate through given w10 install medias (*.iso files), and
# to extract their Windows RE images from them and their details.

set -ex

Checksums=${1}
Log=${Checksums%.sha1}.log
Buffer=$(mktemp)
Output_dir='REs'

PATH=$PATH:~/debug/iso2winre.git

mkdir -v "${Output_dir}"

rhash -cP "${Checksums}" | tee "${Log}"
cat "${Log}" \
| awk '/--\( Verifying / { STARTED=1; next } /^--------/ { STARTED=0 }; STARTED && / OK $/ { sub(/ +OK $/, ""); print }' \
> ${Buffer}

while read Fname <&3; do
  Full_dirn=$(cygpath -w $(realpath "${Output_dir}"))
  Full_name=$(cygpath -w $(realpath "${Fname}"))
  time iso2winre.ps1 "${Full_name}" -to "${Full_dirn}" 2>&1 | tee "${Output_dir}/${Fname}.log"
done 3< ${Buffer}

rm -v ${Buffer}
